### PR TITLE
Fix README code

### PR DESCRIPTION
**Pull request by ligi**
also this line seems to be wrong:

`          setNotificationCallback(firstCharacteristic, callback)`

I guess it should just be

`          setNotificationCallback(firstCharacteristic)`

but did not add to this PR as not 100% sure about this yet

PS: love the humor in the README!

### CODE REVIEW

**Comment by philips77** [comment]
These is a callback parameter in `setNotificationCallback`.

But could you also fix a typo in "Very, very long text that will NOT fit into MTU".

**Comment by ligi** [comment]
> These is a callback parameter in `setNotificationCallback`.
> 


I don't see the parameter there:

Selection_108

> But could you also fix a typo in "Very, very long text that will NOT fit into MTU".

done - but thought this is slang ;-)

**Comment by philips77** [comment]
Oh, true. I don't remember my own lib...

**Comment by ligi** [comment]
I know that feeling ,-)

**Comment by philips77** [comment]
It should be `setNotificationCallback(characteristic).with(callback);`

**Comment by philips77** [comment]
Hi, could you do the last change and I'll merge the PR?

**Comment by ligi** [comment]
sure - but not yet sure how the last change would look like - if you mean

```setNotificationCallback(firstCharacteristic).with(callback);``

callback is not defined anywhere

**Comment by philips77** [comment]
OK, let's change it to:
```java
setNotificationCallback(firstCharacteristic)
	.with((device, data) -> log(Log.INFO, "Notification received: " + data));
```
as this can just demonstrate use of the API.

**Comment by philips77** [comment]
Thanks again for your contribution! I've just merged the PR.

**Pull request merged**
