### PR TITLE
Add extended disconnect callback (closes #110)

### LINKED ISSUE #110: Reason for disconnect is unknown
It's impossible to know the reason for device disconnect. Would it be possible to implement some sort of internal mapping of the Android's GATT errors/states, that is passed along with the 'onDeviceDisconnected' call? Here are some examples of reasons: user disconnected on the remote device, user disconnected on the local device, connection timed out, etc. Or generally speaking it would be nice be able to distinguish intentional and unintentional disconnects.

Related https://github.com/NordicSemiconductor/Android-BLE-Library/pull/21.

### PR DESCRIPTION
**Pull request by sssemil**
This allows registering callback for disconnect but with status report.

### CODE REVIEW

**Comment by philips77** [comment]
Hi, i'm on vacations for 2 weeks. Will look at it when I'm back.

**Comment by sssemil** [comment]
Cool, thanks!

**Comment by sssemil** [comment]
Hey @philips77 how's it going so far?

**Comment by philips77** [comment]
Ok, I'm starting working on it. Sorry for the delay.

**Comment by philips77** [comment]
I will add some more disconnection reasons, but your code looks good.
I was thinking about adding some other way of observing it, like other requests have `done()`, `fail()`, etc, but after some considerations I think your solution is most readable.

**Comment by sssemil** [comment]
Awesome, thanks!

**Comment by philips77** [comment]
Have a look at those. Are you using the version 2.2.0-alpha06 at the moment with your changes? Do you have any other feedback? I'm about to release 2.2.0 as final.

**Comment by sssemil** [comment]
Cool, my colleague is testing it right now. I will write here as soon as he is done.

**Comment by philips77** [comment]
Version 2.2.0-alpha07 released, if it makes easier for you.

**Comment by sssemil** [comment]
Nice, that should make things easier.

**Comment by sssemil** [comment]
Looks good, feel free to release it :)

**Comment by philips77** [comment]
Btw, why didn't you use or modified [BleManagerCallbacks](https://github.com/NordicSemiconductor/Android-BLE-Library/blob/5168c188006a8e5ecab4e187e386b585c9fd5684/ble/src/main/java/no/nordicsemi/android/ble/BleManagerCallbacks.java#L78)? There already was a callback for status changes, which I have forgotten. I think I'll revert the changes and modify the `onDeviceDisconnected` callback to include disconnection reason.

**Comment by sssemil** [comment]
So that API is not broken. That was the original idea, but you suggested to avoid changing it too much. here https://github.com/NordicSemiconductor/Android-BLE-Library/pull/21#issuecomment-412811890, or I misunderstood you :) In any case, both approaches work for me just fine.

**Comment by philips77** [comment]
Oh! Such an old comment! I think it's better with what you suggested back in 2018.

**Comment by philips77** [comment]
You wrote there, that you don't get `onError` in case of a timeout, don't you still get it?

**Comment by sssemil** [comment]
I don't think so, but in any case, having two callbacks with status and action is a little painful to deal with.

**Comment by philips77** [comment]
Have a look at #173. Also, the callbacks aren't called on using the handler, as they should. I'll fix it now.

**Comment by philips77** [comment]
Ok, so I think I now know what I meant and what I will do.
1. I'll leave your disconnect callback, as it is in 2.2.0-alpha07. This is because `onDeviceConnecting`, `onDeviceConnected`, `onServicesDiscovered` and `onDeviceReady` callbacks are now called via `ConnectRequest`, but there's no way to receive unintended disconnection event.
2. I'll create `BondingCallback` with `onBondingRequired`, `onBonded` and `onBondingFailed`. It will be a separate callback with separate setter.
3. I'll deprecate `BleManagerCallbacks`. It will still be called for some time, but I never liked this interface. Since callbacks are now per-request, this one is a legacy thing from version 1 of the library.
4. This means deprecating remaining callbacks, including `onError`.

**Pull request merged**
