### PR TITLE
Add Reliable Write support

### PR DESCRIPTION
**Pull request by philips77**
This PR adds Reliable Write support. Reliable Write is documented in Bluetooth Core Specification, Vol 3, Part G, chapter 4.9.5.

A review is appreciated.

The are issues with the current implementation. Developer needs to call 
```java
beginReliableWrite().enqueue();
writeCharacteristic(...).with(valueCallback).enqueue();
writeCharacteristic(...).with(valueCallback).enqueue();
writeCharacteristic(...).with(valueCallback).enqueue();
```
The `valueCallback` would have to verify the data sent (BUG: actually, now it will get the data sent, not those received, so it will even not work like this), and call `executeReliableWrite()` or `abortReliableWrite()`, depending on the result. This, however, in my opinion, could be done automatically.
To make it automatic, write requests would have to either abort automatically, and notify user about this fact (and clear already enqueued operations?), call some special callback, invoked only in this situation, or allow to enqueue all operations inside the `ReliableWriteRequest`, so that it automatically executes or aborts when done. Not only Write operations are possible during Reliable Write, so it would have to allow any Request to be enqueued, excluding Connect, Disconnect, Bond and Unbond.

So my question is: is anyone using Reliable Write feature in their products? Do you have any feedback, what would be useful, what not? For example, Long Write isn't working when Reliable Write is ongoing, so packets needs to be split automatically it no Splitter is assigned.

### CODE REVIEW

**Comment by esensar** [comment]
Haven't used reliable write before, but it could be useful.
I agree with having it done automatically, there is probably no need for developers to handle verification.

I believe it would make sense to group requests up into one request (your second proposal - `ReliableWriteRequest` containing other requests), which would also make it feel 'atomic'. It would also probably make it easier to work with the library if multiple threads are accessing it (if begin request and other requests were to be made like in the first example, it would be possible that some write requests would get in the reliable write window that developer did not intend to put into the reliable write). Of course, such requests should also be run atomically, not allowing other requests to be processed until it is either executed or aborted.

Thank you for the great library, I hope that my feedback is useful.

**Comment by maragues-kolibree** [comment]
I've never used reliableWrite, tho it looks like something my project could benefit from if it respects the order in which they where issues.

In fact, in https://github.com/NordicSemiconductor/Android-BLE-Library/issues/37 I'm actually enqueuing multiple write requests

**Comment by cirlam** [comment]
I wasn't aware of ReliableWrite until now - but it sounds useful. Certainly automatic verification of the data wrote would be great and I think the suggestion to use a ReliableWriteRequest queue makes most sense to me. 

The automatic behaviour you mentioned in the write request makes sense, but I imagine it may be useful to be able to override the behaviour for Write Success and Write Error (both of these callbacks would need the original request returned to the user, to work out what request it was so you can decide how to handle the error/success), in case you need something bespoke.

**Comment by philips77** [comment]
OK, so I've done some refactoring related to this task. My idea is to:
1. Add an empty `Operation` interface for all `Request`s, that can be done during a connection (that is all, except connect, disconnect, bond, unbond and refresh cache).
2. Create `class OperationSet extends Request`, that could have an internal queue of Operations. Such set would be be performed atomically.
3. Create `class ReliableWriteRequest extends OperationSet`, which would additionally handle begin RW, verification, executing or aborting automatically.

Here are my 4 different proposals for the API:

1. `beginReliableWrite()` returns an object, in which one may enqueue any number of operations:
```java
beginReliableWrite()
      .enqueue(writeCharacteristic(someCharacteristic, someData))
      // Other requests are also possible
      .enqueue(requestMtu(200))
      // Data will be written in the same order
      .enqueue(writeCharacteristic(someCharacteristic, differentData))
      // This will return the OLD data, not 'differentData', as the RW wasn't executed!
      .enqueue(readCharacteristic(someCharacteristic).with(callback))
      // Multiple characteristics may be written during a single RW
      .enqueue(writeCharacteristic(someOtherCharacteristic, importantData), optionalTimeoutForThisOperation)
   // Finally, enqueue the Reliable Write Request in the BleManager
   .enqueue(totalTimeout);
```
2. The same as 1., but with the inner `enqueue(..)` renamed to something else, like `add`.
3. Similar, but with bunch of methods, like `writeCharacteristic(...)` instead of single `enqueue`, which makes it more readable, but the number of lines grows a lot:
```java
beginReliableWrite()
      .writeCharacteristic(someCharacteristic, someData)
      // Other requests are also possible
      .requestMtu(200)
      // Data will be written in the same order
      .writeCharacteristic(someCharacteristic, differentData)
      // This will return the OLD data, not 'differentData', as the RW wasn't executed!
      .readCharacteristic(someCharacteristic).with(callback)
      // Multiple characteristics may be written during a single RW
      .writeCharacteristic(someOtherCharacteristic, importantData) // No option for timeout
   // Finally, enqueue the Reliable Write Request in the BleManager
   .enqueue(totalTimeout);
```
4. Same as 3, but each method is duplicated and has a variant with `timeout`: 
```java
beginReliableWrite()
      .writeCharacteristic(someCharacteristic, someData)
      // Other requests are also possible
      .requestMtu(200)
      // Data will be written in the same order
      .writeCharacteristic(someCharacteristic, differentData)
      // This will return the OLD data, not 'differentData', as the RW wasn't executed!
      .readCharacteristic(someCharacteristic).with(callback)
      // Multiple characteristics may be written during a single RW
      .writeCharacteristic(someOtherCharacteristic, importantData, operationTimeout)
   // Finally, enqueue the Reliable Write Request in the BleManager
   .enqueue(totalTimeout);
```
5. `beginReliableWrite()` just starts a new set, in which all following operations will be enqueued, until it's closed by `executeReliableWrite()`, which will actually start it.
```java
beginReliableWrite();
writeCharacteristic(someCharacteristic, someData).enqueue();
// Other requests are also possible
requestMtu(200).enqueue();
// Data will be written in the same order
writeCharacteristic(someCharacteristic, differentData).enqueue();
// This will return the OLD data, not 'differentData', as the RW wasn't executed!
readCharacteristic(someCharacteristic).with(callback).enqueue();
// Multiple characteristics may be written during a single RW
writeCharacteristic(someOtherCharacteristic, importantData).enqueue();
executeReliableWrite();
```

Again, comments?

**Comment by philips77** [comment]
The timeout could be moved from `enqueue(long)` and `await(long)` to `timeout(long)` method, to make 3. and 4. look better. That would make the 2 first methods deprecated.

**Comment by esensar** [comment]
I feel that 3. option may be the best for developers using this, but it may make library too hard to maintain because of duplication. Same issue with option 4. I still think that 5. option does not make the whole call feel 'atomic' and it could have issues when multiple threads are enqueueing requests.

So it is either option 1 or 2, with 2. option probably being better, making it more obvious that it is composing a reliable write.

**Comment by philips77** [comment]
Btw, Reliable Write must be supported on the firmware side in order to be used. Usually, the characteristic would then get Extended Properties property and [Characteristic Extended Properties descriptor](https://www.bluetooth.com/specifications/gatt/viewer?attributeXmlFile=org.bluetooth.descriptor.gatt.characteristic_extended_properties.xml) with Reliable Write bit set, to make it visible.
Support for RW means that the fw must 1) reply the received values back to the master for verification, 2) store the received values in temporary storage until they are executed, 3) allow to abort the RW and clear the temporary storage.
This can be tested using nRF Connect 4.21, released yesterday.

**Comment by philips77** [comment]
@esensar Valid point with the *atomic* issue in 5. I didn't like 5. as well.
Regarding 3. and 4., the methods would have to return their own requests making the chaining impossible. 
So options 1. or 2. are the only ones possible :) 
Regarding 1. vs 2., the `enqueue` underlines, that the operations will be done in FIFO order. `add` method does not have this meaning.

So the API would look like so:
```java
beginReliableWrite()
      .add(writeCharacteristic(someCharacteristic, someData).split())
      .add(requestMtu(200).done(() -> ...))
      .add(writeCharacteristic(someCharacteristic, differentData))
      .add(readCharacteristic(someCharacteristic).with(callback))
      .add(writeCharacteristic(someOtherCharacteristic, importantData).timeout(optionalTimeoutForThisOperation))
   // Bug: Actually, there is no way, using this API, to set the timeout only for execute or abort operations.
   .timeout(totalTimeout) // <- this is a timeout for the whole request set, not the Execute operation.
   // Finally, enqueue the Reliable Write Request in the BleManager
   .enqueue();
```
I assume that failure of any inner operations would abort the RW, even if it's not the Write request. But that could be parametrized.

**Comment by philips77** [comment]
The PR seems completed with the last 2 commits.
Changes:
1. The `timeout(long)` method added, instead of `enqueue(long)` and `await(long)`, which became deprecated.
2. Most requests may not timeout. That are those that need to wait for the BluetoothGattCallback and Sleep. This is a breaking change. Tests need to be performed when reading/writing triggers bonding.
3. Timeout can be set only to `Connect`, `Disconnect` and `WaitForValueChange`.
4. Reliable Write completed as 2. from above. See `beginReliableWriteRequest()` in `BleManager`.
5. Atomic request queue added, which can be enqueued and executed atomically. See `beginAtomicRequestQueue()` in `BleManager`.
6. Documentation updated.

A review would be appreciated :)

**Comment by philips77** [comment]
Example of use:
```xml
beginReliableWrite()
	.before(device -> log(LogContract.Log.Level.APPLICATION, "Starting Reliable Write..."))
	.add(writeCharacteristic(mLedCharacteristic, BlinkyLED.turnOn())
			.fail((device, status) -> log(Log.WARN, "Command ON failed to sent"))
			.done(device -> log(Log.INFO, "Command ON sent")))
	.add(readCharacteristic(mLedCharacteristic)
			.with(new BlinkyLedDataCallback() {
				@Override
				public void onLedStateChanged(final BluetoothDevice device, final boolean on) {
					log(LogContract.Log.Level.APPLICATION, "LED " + (on ? "ON" : "OFF"));
				}
			})
			.done(device -> log(Log.INFO, "LED status read")))
	.fail((device, status) -> log(Log.WARN, "Reliable Write sub-procedure failed"))
	.done(device -> log(LogContract.Log.Level.APPLICATION, "Reliable Write completed"))
	.enqueue();
```
And atomic queue:
```xml
final RequestQueue aytomicQueue = beginAtomicRequestQueue();
atomicQueue
	.add(writeCharacteristic(mLedCharacteristic, BlinkyLED.turnOn()))
	.add(sleep(100))
	.add(writeCharacteristic(mLedCharacteristic, BlinkyLED.turnOff()))
	.add(waitForNotification(mButtonCharacteristic))
	.add(writeCharacteristic(mLedCharacteristic, BlinkyLED.turnOn()))
	.add(waitForNotification(mButtonCharacteristic).timeout(1000)
		.fail((device, status) -> {
				// This will cancel all not-yet-executed requests and done() callback will be called immediately, as there will be no more requests
				atomicQueue.cancelQueue();
		})) 
	.add(writeCharacteristic(mLedCharacteristic, BlinkyLED.turnOff())
		.done(device -> log(Log.INFO, "Final OFF succeeded"))
		.fail((device, status) -> log(Log.INFO, "Final OFF failed")))
	.add(sleep(2000)
		.done(device -> log(Log.INFO, "Sleep 2000 succeeded"))
		.fail((device, status) -> log(Log.INFO, "Sleep 2000 failed")))
	.done(device -> log(Log.INFO, "Atomic queue complete successfully"))
	.fail((device, status) -> log(Log.INFO, "Atomic queue complete failed with error " + status))
	.enqueue();
```

**Comment by philips77** [comment]
Difference between atomic request queue and reliable write:
1. Reliable Write queue extends Request Queue
2. Reliable Write will abort automatically if any request fails. Can be also aborted with `abort()`.
3. Failed requests in Request Queue will not make the queue to fail.

**Comment by philips77** [comment]
Released in 2.0-beta8.

**Pull request merged**
