### PR TITLE
Add standalone server support to BleServerManager

### PR DESCRIPTION
**Pull request by usikder**
This makes it easier to use BleManager in a purely server role, as described in https://github.com/NordicSemiconductor/Android-BLE-Library/issues/229.

### CODE REVIEW

**Comment by usikder** [comment]
Updated this PR to further flesh out BleManager's standalone server support. In particular, we initialize BleManager's BluetoothGattServer tracking metadata at an earlier time (when the server is open vs when optional client's unrelated services are discovered). We also make BleManager's BluetoothDevice settable so servers can set it since ConnectRequests aren't relevant to standalone servers.

**Comment by philips77** [comment]
How will the API of the`BleManager` work if `BluetoothDevice` if set without connecting? Ideally, I would like it to be in separated objects so that you don't have access to such API, not just that it would return errors when called.

**Comment by usikder** [comment]
Makes sense, I can think more about how to separate this API out more cleanly. For now, do you want to just merge the ServerObserver commit? If so, I can strip the top one off.

**Comment by Moes81** [comment]
Since this thread is still "open", does this mean that stand-alone peripheral still doesn't work?
I'm trying this exact use case, but my callback are not triggered.

**Review by Neoangino — APPROVED** [review]
Supi

**Review by SaintPatricksCoin — APPROVED** [review]
@SaintPatricksCoin

**Comment by philips77** [comment]
I'm closing this PR as we're moving towards Kotlin BLE Library, which should support the only-server case in a better way.

**Pull request closed without merging**
